# Generated by Django 3.0.2 on 2020-01-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(choices=[('Saffron 2 Gram Tin', 'SAF_TSD2G-TIN'), ('Saffron 1 Gram Glass', 'SAF_TSD1G-GLASS'), ('Saffron 2 Gram Glass', 'SAF_TSD2G-GLASS')], default='TSD2G-TIN', max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('Tin', 'Tin'), ('Glass', 'Glass')], default='Tin', max_length=100)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
