# Generated by Django 3.0.2 on 2020-01-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(choices=[('SAF_TSD2G-TIN', 'Saffron 2 Gram Tin'), ('SAF_TSD1G-GLASS', 'Saffron 1 Gram Glass'), ('SAF_TSD2G-GLASS', 'Saffron 2 Gram Glass')], default='TSD2G-TIN', max_length=100),
        ),
    ]
