# Generated by Django 3.0.2 on 2020-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20200120_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('zak', 'Zak'), ('adil', 'Adil'), ('yama', 'Yama')], default='yama', max_length=15)),
                ('packaged_can', models.IntegerField(default=0)),
                ('packaged_usa', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
