# Generated by Django 3.0.2 on 2020-01-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_packager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packager',
            name='name',
            field=models.CharField(choices=[('Zak', 'Zak'), ('Adil', 'Adil'), ('Yama', 'Yama')], default='yama', max_length=15),
        ),
    ]
