# Generated by Django 3.0.2 on 2020-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20200122_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Zak', 'Zak'), ('Adil', 'Adil'), ('Yama', 'Yama')], default='yama', max_length=15)),
                ('reason', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
