# Generated by Django 3.0.2 on 2020-02-01 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20200129_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50)),
                ('invoice_id', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('twoglass', models.IntegerField(default=0)),
                ('oneglass', models.IntegerField(default=0)),
                ('twocan', models.IntegerField(default=0)),
                ('twoglass_p', models.FloatField(default=0.0)),
                ('oneglass_p', models.FloatField(default=0.0)),
                ('twocan_p', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
    ]
