# Generated by Django 3.0.2 on 2020-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.CharField(default='Bob', max_length=20),
        ),
    ]
